name: planmexico
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  speech_to_text: ^7.3.0
  avatar_glow: ^3.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  video_player: ^2.8.6
  video_player_win: ^2.0.0
  webview_flutter: ^4.7.0
  flutter_tts: ^4.2.3
  screenshot: ^3.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/ajolotito.png
    - assets/images/Fondo.png
    - assets/images/ajolote.gif
    - assets/images/logo_aguila.png
    - assets/images/espera.gif
    - assets/images/Ajolote_cubo.gif
    - assets/images/cubo_si.mp4
      